openapi: 3.0.0
info:
  title: A
  description: Exported from Requestly API Client
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
paths:
  /api/v1/search/bangumi/id:
    post:
      summary: Get Bangumi info By ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
            example:
              id: 425998
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
  /api/v1/record/detail_list:
    get:
      summary: Get Detail List Recorder
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
  /api/v1/record/get:
    post:
      summary: Get Record
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bangumi_id:
                  type: number
            example:
              bangumi_id: 425998
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
  /api/v1/record/list:
    get:
      summary: List Recorder
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
  /auth/login:
    post:
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: user
              password: "123456"
      responses:
        "200":
          description: Successful response
  /api/v1/record/add:
    post:
      summary: Recorder Bangumi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bangumi_id:
                  type: number
                user_status:
                  type: number
            example:
              bangumi_id: 425998
              user_status: 1
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
  /auth/register:
    post:
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            example:
              username: user2
              password: "123456"
      responses:
        "200":
          description: Successful response
  /api/v1/search/bangumi:
    post:
      summary: Search Bangumi By Title
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
            example:
              title: Re0
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
  /api/v1/record/update:
    post:
      summary: Update Record
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bangumi_id:
                  type: number
                recorder:
                  type: string
            example:
              bangumi_id: 425998
              recorder: 5|2:12
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
